# What standard to use. This is optional and defaults to VHDL2008.
standard = "2008"
# File names are either absolute or relative to the parent folder of the vhdl_ls.toml file
# [libraries]
# Wildcards and exclude patterns are supported
# lib1.files = [
#     'test/*.vhd',
#     'src/*.vhd',
#     'src/*/*.vhd',
# ]

[libraries]
defaultlib.files = [
  '**/*.vhd'
]
